license:
  report_missing: true
  category: Permissive
  main: apache-2.0
  additional:
    - bsd-new
copyright:
  check: true
exclude:
  extensions:
    - yml
    - yaml
    - html
    - rst
    - conf
    - cfg
  langs:
    - HTML
