# The west manifest file for Bridle for embedded systems based on Zephyr.
#
# Copyright (c) 2021 TiaC Systems
# Copyright (c) 2019-2021 Li-Pro.Net
# SPDX-License-Identifier: Apache-2.0
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this Zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  version: "0.12"

  # If not otherwise specified, the projects below should be obtained
  # from the tiacsys remote.
  defaults:
    remote: tiacsys

  # "remotes" is a list of locations where git repositories are cloned
  # and fetched from.
  remotes:
    - name: tiacsys
      url-base: https://github.com/tiacsys
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  # "projects" is a list of git repositories which make up the TIAC
  # source code. Please add items below based on alphabetical order.
  projects:

    # The Zephyr RTOS fork in the TIAC organization, along with the subset
    # of its modules which TIAC imports (partly but not yet) directly.
    - name: zephyr
      path: zephyr
      remote: tiacsys
      repo-path: zephyr
      revision: tiacsys/v3.1-branch
      clone-depth: 5000
      # import submodules from Zephyr manifest
      import:
        # In addition to the Zephyr repository itself, TIAC also
        # imports the contents of Zephyr/west.yml at the above
        # revision. Only the projects explicitly named in the
        # following allowlist are imported.
        #
        # Note that the Zephyr west extensions (like 'build', 'flash',
        # 'debug', etc.) are automatically provided by this import, so
        # there's no need to add a redundant west-commands: key for
        # the Zephyr project.
        #
        # Please keep this list sorted alphabetically.
        name-allowlist:
          - canopennode
          - cmsis
          - civetweb
          - edtt
          - fatfs
          - hal_altera
          - hal_espressif
          - hal_nordic
          - hal_stm32
          - hal_xtensa
          - libmetal
          - littlefs
          - loramac-node
          - lvgl
          - mbedtls
          - mcumgr
          - mipi-sys-t
          - net-tools
          - open-amp
          - openthread
          - segger
          - tinycbor
          - tinycrypt

  # West-related configuration for the Bridle repository.
  self:
    # This repository should be cloned to workspace/bridle.
    path: bridle
    # This line configures west extensions which are currently
    # only for internal use by TIAC maintainers; import build
    # commands from Zephyr repo.
    west-commands: scripts/west-commands.yml
