[manifest]
group-filter = ["-babblesim"]

[[manifest.projects]]
name = "ubxlib"
url = "https://github.com/tiacsys/ubxlib"
revision = "c4f76f17feb96345ad93c7f1009d2d4abc517c92"
path = "modules/lib/ubxlib"

[manifest.projects.nix]
hash = "sha256-hRRMhZaO1UEjx1zcgX6PZfNX2SVa1A4KEWAvMglBBfk="

[[manifest.projects]]
name = "zephyr"
url = "https://github.com/tiacsys/zephyr"
revision = "a50d3b9a4d4f19861b5cf3ae08353ad96ae3ee1a"
clone-depth = 5000
west-commands = "scripts/west-commands.yml"

[manifest.projects.userdata]
west-commands-path = "scripts/west_commands"

[manifest.projects.nix]
hash = "sha256-An69qG9OpyWASCclGdyPdFc71OIEKpSA7R22JjFWMoU="

[[manifest.projects]]
name = "canopennode"
url = "https://github.com/zephyrproject-rtos/canopennode"
revision = "dec12fa3f0d790cafa8414a4c2930ea71ab72ffd"
path = "modules/lib/canopennode"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-BbmEjeMzKznRDx329PIkmPMCGI+du6wiOj+3X7Ap1HQ="

[[manifest.projects]]
name = "chre"
url = "https://github.com/zephyrproject-rtos/chre"
revision = "3b32c76efee705af146124fb4190f71be5a4e36e"
path = "modules/lib/chre"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-7SdP9zSKZ+6s+nkIcIbjZSnacq2/t06DiR2gcaL07T4="

[[manifest.projects]]
name = "psa-arch-tests"
url = "https://github.com/zephyrproject-rtos/psa-arch-tests"
revision = "2cadb02a72eacda7042505dcbdd492371e8ce024"
path = "modules/tee/tf-m/psa-arch-tests"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-oYpqLIbtKsNHQ9FQjhSM8Rvd/VM4M+ETO5hum2fZVq8="

[[manifest.projects]]
name = "tf-m-tests"
url = "https://github.com/zephyrproject-rtos/tf-m-tests"
revision = "d552e4f18b92032bd335d5e3aa312f6acd82a83b"
path = "modules/tee/tf-m/tf-m-tests"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-UUy4OJeOp0fbXVV+w/ypDZPFDVk13MSyeaTqMOHZh7g="

[[manifest.projects]]
name = "acpica"
url = "https://github.com/zephyrproject-rtos/acpica"
revision = "8d24867bc9c9d81c81eeac59391cda59333affd4"
path = "modules/lib/acpica"

[manifest.projects.nix]
hash = "sha256-DwE7etw6DqWHb/NvGwep19RYsVmA/CBxvTnFVmqf2Io="

[[manifest.projects]]
name = "cmsis"
url = "https://github.com/zephyrproject-rtos/cmsis"
revision = "4b96cbb174678dcd3ca86e11e1f24bc5f8726da0"
path = "modules/hal/cmsis"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-vzCbE69wCMLIjrSz1m8yspgVCto4JSm4Qg5zY/Ozg+k="

[[manifest.projects]]
name = "edtt"
url = "https://github.com/zephyrproject-rtos/edtt"
revision = "8d7b543d4d2f2be0f78481e4e1d8d73a88024803"
path = "tools/edtt"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-LckP4twBiTUU4emwoTuGszbNRhiFbimOkaScT4P8eaA="

[[manifest.projects]]
name = "fatfs"
url = "https://github.com/zephyrproject-rtos/fatfs"
revision = "427159bf95ea49b7680facffaa29ad506b42709b"
path = "modules/fs/fatfs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-5l3hJazG8BoLZ0QxfSFc98uKArIGAFD1P8D6tsKMRt4="

[[manifest.projects]]
name = "hal_altera"
url = "https://github.com/zephyrproject-rtos/hal_altera"
revision = "0d225ddd314379b32355a00fb669eacf911e750d"
path = "modules/hal/altera"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-H2C+3ASsC5O/mA+O5EJqfoJgx0BhSN0W3OhWNHVQxRU="

[[manifest.projects]]
name = "hal_ambiq"
url = "https://github.com/zephyrproject-rtos/hal_ambiq"
revision = "367ae6a0396e3074bebbd55ef72f8e577168e567"
path = "modules/hal/ambiq"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-GvRT4nPQ3V0HMifLFJ4V5dopIViTwM/H5UqV4vqu0TU="

[[manifest.projects]]
name = "hal_atmel"
url = "https://github.com/zephyrproject-rtos/hal_atmel"
revision = "56d60ebc909ad065bf6554cee73487969857614b"
path = "modules/hal/atmel"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-axwXPNITDqPDccjs6oUpAvVZwFkMpM/bkEv6TVYcvo0="

[[manifest.projects]]
name = "hal_gigadevice"
url = "https://github.com/zephyrproject-rtos/hal_gigadevice"
revision = "2994b7dde8b0b0fa9b9c0ccb13474b6a486cddc3"
path = "modules/hal/gigadevice"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Cgcc+7tJy0ryQG4ynrlv7OmNe3OW2kMx1mStGROgA5o="

[[manifest.projects]]
name = "hal_infineon"
url = "https://github.com/zephyrproject-rtos/hal_infineon"
revision = "f25734a72c585f6675e8254a382e80e78a3cd03a"
path = "modules/hal/infineon"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-55gB6+7oUUKV9h/TkBgfW7dVz/2saR+TdnrDDB/Vb+o="

[[manifest.projects]]
name = "hal_intel"
url = "https://github.com/zephyrproject-rtos/hal_intel"
revision = "0905a528623de56b1bedf817536321bcdbc0efae"
path = "modules/hal/intel"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-JVFrNQ0fgHv0myY/nDSiGYR5G9Vn5gFmI6aT/pEnbyI="

[[manifest.projects]]
name = "hal_microchip"
url = "https://github.com/zephyrproject-rtos/hal_microchip"
revision = "71eba057c0cb7fc11b6f33eb40a82f1ebe2c571c"
path = "modules/hal/microchip"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-qtbwdJHUe3aDSffBIxwFA9sya7ETRUrBMNeOFRZjXWw="

[[manifest.projects]]
name = "hal_nordic"
url = "https://github.com/zephyrproject-rtos/hal_nordic"
revision = "ab5cb2e2faeb1edfad7a25286dcb513929ae55da"
path = "modules/hal/nordic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-NWeIfSmmPipgy4qsS2RPVF6VOZiX/eHt6udg/Z8MrNw="

[[manifest.projects]]
name = "hal_nuvoton"
url = "https://github.com/zephyrproject-rtos/hal_nuvoton"
revision = "466c3eed9c98453fb23953bf0e0427fea01924be"
path = "modules/hal/nuvoton"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-0T+E4JUtSiWsypVPYnlRvDNr1otXRzLDCvx2TDQKS1Y="

[[manifest.projects]]
name = "hal_nxp"
url = "https://github.com/zephyrproject-rtos/hal_nxp"
revision = "bee15c31e19ff1982583d9b750ef844d64320160"
path = "modules/hal/nxp"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-r0K/Lgm9UhTn1LVrn/qL0a5BuTmi0VnfyPMVazVg5yo="

[[manifest.projects]]
name = "hal_openisa"
url = "https://github.com/zephyrproject-rtos/hal_openisa"
revision = "eabd530a64d71de91d907bad257cd61aacf607bc"
path = "modules/hal/openisa"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-krI/9sr57ZjerDKb9lQvIOD+q6vfiXqRGqV7cbW9Bqs="

[[manifest.projects]]
name = "hal_quicklogic"
url = "https://github.com/zephyrproject-rtos/hal_quicklogic"
revision = "bad894440fe72c814864798c8e3a76d13edffb6c"
path = "modules/hal/quicklogic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-EFeySS+Kz7RecJ7it5CVAdP0y9m2gCCGl0Pu6l21+TQ="

[[manifest.projects]]
name = "hal_renesas"
url = "https://github.com/zephyrproject-rtos/hal_renesas"
revision = "a8cd5ed480a31982a86dab8952ac8baaf646c3cb"
path = "modules/hal/renesas"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-LIHPGBEni4uO8sEZx1ninSUkFhS25vZ7yeV99nKvF+A="

[[manifest.projects]]
name = "hal_rpi_pico"
url = "https://github.com/zephyrproject-rtos/hal_rpi_pico"
revision = "fba7162cc7bee06d0149622bbcaac4e41062d368"
path = "modules/hal/rpi_pico"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-qv0GPlBQ0np8a0obi5pt6LyxKiTIqWEhoG7vI4jLAwc="

[[manifest.projects]]
name = "hal_silabs"
url = "https://github.com/zephyrproject-rtos/hal_silabs"
revision = "a09dd1b82b24aa3060e162c0dfa40026c0dba450"
path = "modules/hal/silabs"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-YQGIk/Jd5Iz5URF35nNFqEOY/WgoKOoQF+Ff+eeYZZI="

[[manifest.projects]]
name = "hal_st"
url = "https://github.com/zephyrproject-rtos/hal_st"
revision = "b77157f6bc4395e398d90ab02a7d2cbc01ab2ce7"
path = "modules/hal/st"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-zjRgI7ZzDcztvChaLohl3rXAaKTMdW9A2G306RoC2Xc="

[[manifest.projects]]
name = "hal_stm32"
url = "https://github.com/zephyrproject-rtos/hal_stm32"
revision = "6443e5c4d391c3e9e283c5728cd07d855e663965"
path = "modules/hal/stm32"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-u1V1qqoCxc2yAgLhRRUFdHgtdMgB1rXjArepbwavsxA="

[[manifest.projects]]
name = "hal_telink"
url = "https://github.com/zephyrproject-rtos/hal_telink"
revision = "4226c7fc17d5a34e557d026d428fc766191a0800"
path = "modules/hal/telink"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-QBOMtj95FNrJ9q9/dwmCG5Ro22jgxVq6J7OUuwsaXmI="

[[manifest.projects]]
name = "hal_ti"
url = "https://github.com/zephyrproject-rtos/hal_ti"
revision = "b85f86e51fc4d47c4c383d320d64d52d4d371ae4"
path = "modules/hal/ti"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-NaXcMhV3GG+BexuQx3S4vtEchLgKasMlo1NJ+V56JBk="

[[manifest.projects]]
name = "hal_xtensa"
url = "https://github.com/zephyrproject-rtos/hal_xtensa"
revision = "a2d658525b16c57bea8dd565f5bd5167e4b9f1ee"
path = "modules/hal/xtensa"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-1EtwoP89uqMo6wpoB2RH4h6Qvj3U8yX8K0tCMyM+zeo="

[[manifest.projects]]
name = "libmetal"
url = "https://github.com/zephyrproject-rtos/libmetal"
revision = "243eed541b9c211a2ce8841c788e62ddce84425e"
path = "modules/hal/libmetal"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-wCsYllPeDKx4P5gBGEFDcY4QNbMdwrd+5h5GZ8tEsJM="

[[manifest.projects]]
name = "liblc3"
url = "https://github.com/zephyrproject-rtos/liblc3"
revision = "1a5938ebaca4f13fe79ce074f5dee079783aa29f"
path = "modules/lib/liblc3"

[manifest.projects.nix]
hash = "sha256-nQJgF/cWoCx5TkX4xOaLB9SzvhVXPY29bLh7UwPMWEE="

[[manifest.projects]]
name = "littlefs"
url = "https://github.com/zephyrproject-rtos/littlefs"
revision = "408c16a909dd6cf128874a76f21c793798c9e423"
path = "modules/fs/littlefs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-r0YCwuH5RQill5xtjPUV5NUsKqs3U0k8I2W5knKXVb8="

[[manifest.projects]]
name = "loramac-node"
url = "https://github.com/zephyrproject-rtos/loramac-node"
revision = "fb00b383072518c918e2258b0916c996f2d4eebe"
path = "modules/lib/loramac-node"

[manifest.projects.nix]
hash = "sha256-mzvH8wh+si6q0QCoPl/mAm0QI3PkXGY3uaOMkimQtqg="

[[manifest.projects]]
name = "lvgl"
url = "https://github.com/zephyrproject-rtos/lvgl"
revision = "2b498e6f36d6b82ae1da12c8b7742e318624ecf5"
path = "modules/lib/gui/lvgl"

[manifest.projects.nix]
hash = "sha256-esrGS2Mz7RnT91O/wvMwxhtRemf7aq2iNAApCNonkCU="

[[manifest.projects]]
name = "mbedtls"
url = "https://github.com/zephyrproject-rtos/mbedtls"
revision = "2f24831ee13d399ce019c4632b0bcd440a713f7c"
path = "modules/crypto/mbedtls"
groups = ["crypto"]

[manifest.projects.nix]
hash = "sha256-IgQFVvsXcAbxvVcrv3U/eEt4fCo+ramzYswI97BAExE="

[[manifest.projects]]
name = "mcuboot"
url = "https://github.com/zephyrproject-rtos/mcuboot"
revision = "898a1ca64a759541d9fcc37fef921db93d99ad70"
path = "bootloader/mcuboot"

[manifest.projects.nix]
hash = "sha256-1cuJ9/sLKWkxmB6knocQpwfu/lEoaiclZs1RSicdoE4="

[[manifest.projects]]
name = "mipi-sys-t"
url = "https://github.com/zephyrproject-rtos/mipi-sys-t"
revision = "71ace1f5caa03e56c8740a09863e685efb4b2360"
path = "modules/debug/mipi-sys-t"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-9Ps3igspEKar258fU2GbLRE17zyifFyGQ/2hF+lfL4w="

[[manifest.projects]]
name = "net-tools"
url = "https://github.com/zephyrproject-rtos/net-tools"
revision = "7c7a856814d7f27509c8511fef14cec21f7d0c30"
path = "tools/net-tools"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-T1hnDzDRAGQavm6NNzIFokWsouFJ3rkoAmcZRbvhqQc="

[[manifest.projects]]
name = "open-amp"
url = "https://github.com/zephyrproject-rtos/open-amp"
revision = "da78aea63159771956fe0c9263f2e6985b66e9d5"
path = "modules/lib/open-amp"

[manifest.projects.nix]
hash = "sha256-7yae0X7zqDPA4CUfGU3LgNBh7qyKGIPLUv6dn/d65Fg="

[[manifest.projects]]
name = "openthread"
url = "https://github.com/zephyrproject-rtos/openthread"
revision = "3873c6fcd5a8a9dd01b71e8efe32ef5dc7923bb1"
path = "modules/lib/openthread"

[manifest.projects.nix]
hash = "sha256-qcL0oBtOYaHvgzAZ9KzghA4DkVUGW78f1s1tMpVsA4I="

[[manifest.projects]]
name = "picolibc"
url = "https://github.com/zephyrproject-rtos/picolibc"
revision = "764ef4e401a8f4c6a86ab723533841f072885a5b"
path = "modules/lib/picolibc"

[manifest.projects.nix]
hash = "sha256-5W/+vorhOP/MD19JYzHJfZTkWMM7sKUQqzTDA/7rxZs="

[[manifest.projects]]
name = "segger"
url = "https://github.com/zephyrproject-rtos/segger"
revision = "b011c45b585e097d95d9cf93edf4f2e01588d3cd"
path = "modules/debug/segger"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-otxrP9Z4fUlJvdQ52jIXz9Bb6Fy3mr/jEFx9lhz0QlE="

[[manifest.projects]]
name = "tinycrypt"
url = "https://github.com/zephyrproject-rtos/tinycrypt"
revision = "1012a3ebee18c15ede5efc8332ee2fc37817670f"
path = "modules/crypto/tinycrypt"
groups = ["crypto"]

[manifest.projects.nix]
hash = "sha256-JQmkN+ircGU5Ald1+Q4lysuxhZLg2mJpNQ92+agMoCQ="

[[manifest.projects]]
name = "trusted-firmware-m"
url = "https://github.com/zephyrproject-rtos/trusted-firmware-m"
revision = "bdc4df1734b870de43237d56eb1b2a7af016ee95"
path = "modules/tee/tf-m/trusted-firmware-m"
groups = ["tee"]

[manifest.projects.nix]
hash = "sha256-2TENNmySRdqd975ACw7/oBkr8oJoV4CUjDnmrGJ20r4="

[[manifest.projects]]
name = "trusted-firmware-a"
url = "https://github.com/zephyrproject-rtos/trusted-firmware-a"
revision = "421dc050278287839f5c70019bd6aec617f2bbdb"
path = "modules/tee/tf-a/trusted-firmware-a"
groups = ["tee"]

[manifest.projects.nix]
hash = "sha256-XsjRUe0Cr5bd+rOzoS+Hquh9k2nKwDKt2+up24aCOgk="

[manifest.self]
path = "bridle"
west-commands = "scripts/west-commands.yml"
