[manifest]
group-filter = ["-babblesim"]

[[manifest.projects]]
name = "ubxlib"
url = "https://github.com/tiacsys/ubxlib"
revision = "775806f3feacc8e2816465e50550d74fd4e27ac9"
path = "modules/lib/ubxlib"

[manifest.projects.nix]
hash = "sha256-E7b40VGy7qQ26eXRbSVqhIuJiDOWqJ6+oYqQmnbo7AM="

[[manifest.projects]]
name = "zephyr"
url = "https://github.com/tiacsys/zephyr"
revision = "3992364eb88dda0dc3af68b09cbe03de6d88756d"
clone-depth = 5000
west-commands = "scripts/west-commands.yml"

[manifest.projects.userdata]
west-commands-path = "scripts/west_commands"

[manifest.projects.nix]
hash = "sha256-s571cJA19QPkU/qki4QTw+uHZ2e9NyvYSEl3OrwZZMM="

[[manifest.projects]]
name = "canopennode"
url = "https://github.com/zephyrproject-rtos/canopennode"
revision = "dec12fa3f0d790cafa8414a4c2930ea71ab72ffd"
path = "modules/lib/canopennode"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-BbmEjeMzKznRDx329PIkmPMCGI+du6wiOj+3X7Ap1HQ="

[[manifest.projects]]
name = "chre"
url = "https://github.com/zephyrproject-rtos/chre"
revision = "3b32c76efee705af146124fb4190f71be5a4e36e"
path = "modules/lib/chre"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-7SdP9zSKZ+6s+nkIcIbjZSnacq2/t06DiR2gcaL07T4="

[[manifest.projects]]
name = "psa-arch-tests"
url = "https://github.com/zephyrproject-rtos/psa-arch-tests"
revision = "2cadb02a72eacda7042505dcbdd492371e8ce024"
path = "modules/tee/tf-m/psa-arch-tests"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-oYpqLIbtKsNHQ9FQjhSM8Rvd/VM4M+ETO5hum2fZVq8="

[[manifest.projects]]
name = "tf-m-tests"
url = "https://github.com/zephyrproject-rtos/tf-m-tests"
revision = "85f533a4aa5b4fe31247676a923db7453eb4429c"
path = "modules/tee/tf-m/tf-m-tests"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-WR/3UstEoAAxcf8XXpjBnpm1ksxfw7py2P6WjPQ0Irs="

[[manifest.projects]]
name = "acpica"
url = "https://github.com/zephyrproject-rtos/acpica"
revision = "da5f2721e1c7f188fe04aa50af76f4b94f3c3ea3"
path = "modules/lib/acpica"

[manifest.projects.nix]
hash = "sha256-y2if6wP0Xm98iFwDkV0Ot1BIv6KhI1T3MaY5Ba0oCCs="

[[manifest.projects]]
name = "cmsis"
url = "https://github.com/zephyrproject-rtos/cmsis"
revision = "4b96cbb174678dcd3ca86e11e1f24bc5f8726da0"
path = "modules/hal/cmsis"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-vzCbE69wCMLIjrSz1m8yspgVCto4JSm4Qg5zY/Ozg+k="

[[manifest.projects]]
name = "edtt"
url = "https://github.com/zephyrproject-rtos/edtt"
revision = "64e5105ad82390164fb73fc654be3f73a608209a"
path = "tools/edtt"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-AK4zYIHn0XnkKDl9YGo1lV/2Ea6wLw0rJbzpMA8JZ9w="

[[manifest.projects]]
name = "fatfs"
url = "https://github.com/zephyrproject-rtos/fatfs"
revision = "427159bf95ea49b7680facffaa29ad506b42709b"
path = "modules/fs/fatfs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-5l3hJazG8BoLZ0QxfSFc98uKArIGAFD1P8D6tsKMRt4="

[[manifest.projects]]
name = "hal_altera"
url = "https://github.com/zephyrproject-rtos/hal_altera"
revision = "0d225ddd314379b32355a00fb669eacf911e750d"
path = "modules/hal/altera"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-H2C+3ASsC5O/mA+O5EJqfoJgx0BhSN0W3OhWNHVQxRU="

[[manifest.projects]]
name = "hal_ambiq"
url = "https://github.com/zephyrproject-rtos/hal_ambiq"
revision = "94dd874cd726ba8185a301e78337c5c39685123f"
path = "modules/hal/ambiq"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-1YDU9LqO5XqMnUtLcYUS/VK0FnCe243QsO9683MpzB4="

[[manifest.projects]]
name = "hal_atmel"
url = "https://github.com/zephyrproject-rtos/hal_atmel"
revision = "d6221e73d76a4a31d802e0657342fcbda77e21ae"
path = "modules/hal/atmel"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-jciNzeOiYhlyYRAPgtg/gVjpF4pUyt7Zk+1rssoHrz0="

[[manifest.projects]]
name = "hal_gigadevice"
url = "https://github.com/zephyrproject-rtos/hal_gigadevice"
revision = "2994b7dde8b0b0fa9b9c0ccb13474b6a486cddc3"
path = "modules/hal/gigadevice"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Cgcc+7tJy0ryQG4ynrlv7OmNe3OW2kMx1mStGROgA5o="

[[manifest.projects]]
name = "hal_infineon"
url = "https://github.com/zephyrproject-rtos/hal_infineon"
revision = "b1a47231e8671c882c5f055f9f10c32b18133d08"
path = "modules/hal/infineon"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-gt45U8NZ7SGBN2L9RxMNNsw7HoIa8dxP1wGNX3mk8g4="

[[manifest.projects]]
name = "hal_intel"
url = "https://github.com/zephyrproject-rtos/hal_intel"
revision = "7b4c25669f1513b0d6d6ee78ee42340d91958884"
path = "modules/hal/intel"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-h2r4jKmqVaGoTxfJKQ+S2Zegg/MAfCiIBrpBHtVnsrA="

[[manifest.projects]]
name = "hal_microchip"
url = "https://github.com/zephyrproject-rtos/hal_microchip"
revision = "68575aa28cd33c68b3b8d66f510d15746c57fdb5"
path = "modules/hal/microchip"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Q2mJFu9PM7vWB+H9rUVkiUnId5mDDs6ZKyQJ2kF33tQ="

[[manifest.projects]]
name = "hal_nordic"
url = "https://github.com/zephyrproject-rtos/hal_nordic"
revision = "a3aacc7e43dec644a9ddfee4aa578a4f8ff54610"
path = "modules/hal/nordic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Pnu0yp+LYz7WTbvO+bXg1PaFxF/zkoNJt250uu8iEkw="

[[manifest.projects]]
name = "hal_nuvoton"
url = "https://github.com/zephyrproject-rtos/hal_nuvoton"
revision = "ab342e6915bf7bff2203a20985754f6dbdb5343d"
path = "modules/hal/nuvoton"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-LYbv5A7IGICZ5/uDZe8cyCMpV1HiitBXbZ3QbgHku0s="

[[manifest.projects]]
name = "hal_nxp"
url = "https://github.com/zephyrproject-rtos/hal_nxp"
revision = "8c354a918c1272b40ad9b4ffecac1d89125efbe6"
path = "modules/hal/nxp"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-JJ44H2MDADrgTGwnnkaxoNQnVsVZJ6zimbB+2ZuhRt4="

[[manifest.projects]]
name = "hal_openisa"
url = "https://github.com/zephyrproject-rtos/hal_openisa"
revision = "eabd530a64d71de91d907bad257cd61aacf607bc"
path = "modules/hal/openisa"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-krI/9sr57ZjerDKb9lQvIOD+q6vfiXqRGqV7cbW9Bqs="

[[manifest.projects]]
name = "hal_quicklogic"
url = "https://github.com/zephyrproject-rtos/hal_quicklogic"
revision = "bad894440fe72c814864798c8e3a76d13edffb6c"
path = "modules/hal/quicklogic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-EFeySS+Kz7RecJ7it5CVAdP0y9m2gCCGl0Pu6l21+TQ="

[[manifest.projects]]
name = "hal_renesas"
url = "https://github.com/zephyrproject-rtos/hal_renesas"
revision = "e3560c79db1a002014f061c611cd84a99e4f33de"
path = "modules/hal/renesas"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-tQePVx8sx0xVWBVl7uxlXbot+64K/vlD3ThM6c3xYns="

[[manifest.projects]]
name = "hal_rpi_pico"
url = "https://github.com/zephyrproject-rtos/hal_rpi_pico"
revision = "fba7162cc7bee06d0149622bbcaac4e41062d368"
path = "modules/hal/rpi_pico"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-qv0GPlBQ0np8a0obi5pt6LyxKiTIqWEhoG7vI4jLAwc="

[[manifest.projects]]
name = "hal_silabs"
url = "https://github.com/zephyrproject-rtos/hal_silabs"
revision = "0c39ee28be31c59a98ed490c3811f68caa1fcbd3"
path = "modules/hal/silabs"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-rRDkGRR115FpLOpUUIwVcFVCeJqBC5PDtvBFpWKHa3M="

[[manifest.projects]]
name = "hal_st"
url = "https://github.com/zephyrproject-rtos/hal_st"
revision = "b77157f6bc4395e398d90ab02a7d2cbc01ab2ce7"
path = "modules/hal/st"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-zjRgI7ZzDcztvChaLohl3rXAaKTMdW9A2G306RoC2Xc="

[[manifest.projects]]
name = "hal_stm32"
url = "https://github.com/zephyrproject-rtos/hal_stm32"
revision = "ed93098718d5c727d2fac5ef27023a2a14763e32"
path = "modules/hal/stm32"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-VTjLW3SQvoZn16kC/i/LmMQdzwjlY7hFIbMqzUtmTx8="

[[manifest.projects]]
name = "hal_telink"
url = "https://github.com/zephyrproject-rtos/hal_telink"
revision = "38573af589173259801ae6c2b34b7d4c9e626746"
path = "modules/hal/telink"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-H50e/YCXk1oa7MSyW1czZ09S4GOhp7e2BDIKyr/Fn5o="

[[manifest.projects]]
name = "hal_ti"
url = "https://github.com/zephyrproject-rtos/hal_ti"
revision = "b85f86e51fc4d47c4c383d320d64d52d4d371ae4"
path = "modules/hal/ti"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-NaXcMhV3GG+BexuQx3S4vtEchLgKasMlo1NJ+V56JBk="

[[manifest.projects]]
name = "hal_xtensa"
url = "https://github.com/zephyrproject-rtos/hal_xtensa"
revision = "a2d658525b16c57bea8dd565f5bd5167e4b9f1ee"
path = "modules/hal/xtensa"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-1EtwoP89uqMo6wpoB2RH4h6Qvj3U8yX8K0tCMyM+zeo="

[[manifest.projects]]
name = "libmetal"
url = "https://github.com/zephyrproject-rtos/libmetal"
revision = "243eed541b9c211a2ce8841c788e62ddce84425e"
path = "modules/hal/libmetal"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-wCsYllPeDKx4P5gBGEFDcY4QNbMdwrd+5h5GZ8tEsJM="

[[manifest.projects]]
name = "liblc3"
url = "https://github.com/zephyrproject-rtos/liblc3"
revision = "1a5938ebaca4f13fe79ce074f5dee079783aa29f"
path = "modules/lib/liblc3"

[manifest.projects.nix]
hash = "sha256-nQJgF/cWoCx5TkX4xOaLB9SzvhVXPY29bLh7UwPMWEE="

[[manifest.projects]]
name = "littlefs"
url = "https://github.com/zephyrproject-rtos/littlefs"
revision = "408c16a909dd6cf128874a76f21c793798c9e423"
path = "modules/fs/littlefs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-r0YCwuH5RQill5xtjPUV5NUsKqs3U0k8I2W5knKXVb8="

[[manifest.projects]]
name = "loramac-node"
url = "https://github.com/zephyrproject-rtos/loramac-node"
revision = "fb00b383072518c918e2258b0916c996f2d4eebe"
path = "modules/lib/loramac-node"

[manifest.projects.nix]
hash = "sha256-mzvH8wh+si6q0QCoPl/mAm0QI3PkXGY3uaOMkimQtqg="

[[manifest.projects]]
name = "lvgl"
url = "https://github.com/zephyrproject-rtos/lvgl"
revision = "2b498e6f36d6b82ae1da12c8b7742e318624ecf5"
path = "modules/lib/gui/lvgl"

[manifest.projects.nix]
hash = "sha256-esrGS2Mz7RnT91O/wvMwxhtRemf7aq2iNAApCNonkCU="

[[manifest.projects]]
name = "mbedtls"
url = "https://github.com/zephyrproject-rtos/mbedtls"
revision = "3217c450180fd5e817601c6f479116de69e57461"
path = "modules/crypto/mbedtls"
groups = ["crypto"]

[manifest.projects.nix]
hash = "sha256-Q0h+t8lNE07sPlfjjupWkArdTt1wV7IgU4u9FGsZzjk="

[[manifest.projects]]
name = "mcuboot"
url = "https://github.com/zephyrproject-rtos/mcuboot"
revision = "d4394c2f9b76e0a7b758441cea3a8ceb896f66c8"
path = "bootloader/mcuboot"

[manifest.projects.nix]
hash = "sha256-ARgDJ5wg+SkXN71kSBytwEk2SQwg1MT0M+zU4LZhOns="

[[manifest.projects]]
name = "mipi-sys-t"
url = "https://github.com/zephyrproject-rtos/mipi-sys-t"
revision = "a819419603a2dfcb47f7f39092e1bc112e45d1ef"
path = "modules/debug/mipi-sys-t"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-O5BkXoaCj3xxRsaoarDcCSxhovhH0ihvmY0COy6BQK0="

[[manifest.projects]]
name = "net-tools"
url = "https://github.com/zephyrproject-rtos/net-tools"
revision = "cd2eb1858a1570b49241e18fc1e1cd849a450af2"
path = "tools/net-tools"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-EkisIg3DJBgULxyIVB7P1muHVlZCqh50KbbV/dfCnlY="

[[manifest.projects]]
name = "open-amp"
url = "https://github.com/zephyrproject-rtos/open-amp"
revision = "da78aea63159771956fe0c9263f2e6985b66e9d5"
path = "modules/lib/open-amp"

[manifest.projects.nix]
hash = "sha256-7yae0X7zqDPA4CUfGU3LgNBh7qyKGIPLUv6dn/d65Fg="

[[manifest.projects]]
name = "openthread"
url = "https://github.com/zephyrproject-rtos/openthread"
revision = "49c59ec519cc8b49dd58978d1bc80b7ae7ba88d0"
path = "modules/lib/openthread"

[manifest.projects.nix]
hash = "sha256-/t8aoOdinVcXEmsKmErr7dXWHO6v370/ABulua3+ATc="

[[manifest.projects]]
name = "picolibc"
url = "https://github.com/zephyrproject-rtos/picolibc"
revision = "764ef4e401a8f4c6a86ab723533841f072885a5b"
path = "modules/lib/picolibc"

[manifest.projects.nix]
hash = "sha256-5W/+vorhOP/MD19JYzHJfZTkWMM7sKUQqzTDA/7rxZs="

[[manifest.projects]]
name = "segger"
url = "https://github.com/zephyrproject-rtos/segger"
revision = "b011c45b585e097d95d9cf93edf4f2e01588d3cd"
path = "modules/debug/segger"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-otxrP9Z4fUlJvdQ52jIXz9Bb6Fy3mr/jEFx9lhz0QlE="

[[manifest.projects]]
name = "tinycrypt"
url = "https://github.com/zephyrproject-rtos/tinycrypt"
revision = "1012a3ebee18c15ede5efc8332ee2fc37817670f"
path = "modules/crypto/tinycrypt"
groups = ["crypto"]

[manifest.projects.nix]
hash = "sha256-JQmkN+ircGU5Ald1+Q4lysuxhZLg2mJpNQ92+agMoCQ="

[[manifest.projects]]
name = "trusted-firmware-m"
url = "https://github.com/zephyrproject-rtos/trusted-firmware-m"
revision = "785d87492490069b62170159fcf21c385f90f4eb"
path = "modules/tee/tf-m/trusted-firmware-m"
groups = ["tee"]

[manifest.projects.nix]
hash = "sha256-QATFZBBWeJeyF5hyOU9fsd5LQLueeJgDpeI7sj7xFf4="

[[manifest.projects]]
name = "trusted-firmware-a"
url = "https://github.com/zephyrproject-rtos/trusted-firmware-a"
revision = "421dc050278287839f5c70019bd6aec617f2bbdb"
path = "modules/tee/tf-a/trusted-firmware-a"
groups = ["tee"]

[manifest.projects.nix]
hash = "sha256-XsjRUe0Cr5bd+rOzoS+Hquh9k2nKwDKt2+up24aCOgk="

[manifest.self]
path = "bridle"
west-commands = "scripts/west-commands.yml"
