- available: true
  connected: true
  fixtures:
    - gpio_loopback
    - pwm_loopback
    - spi_loopback
    - i2c_bus_short
  id: DT04ATV0
  platform: magpie_f777ni/stm32f777xx
  product: TiaC Magpie F777NI
  runner: openocd
  serial: /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DT04ATV0-if00-port0
