# Copyright (c) 2021 TiaC Systems
# Copyright (c) 2021 Li-Pro.Net
# SPDX-License-Identifier: Apache-2.0

name: Documentation Remove

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - 'v*-branch'
    paths:
      - 'doc/**'
      - '**.rst'
      - 'include/**'
      - '.known-issues/doc/**'
      - '**/Kconfig*'
      - 'west.yml'
      - '.github/workflows/doc-*.yml'

jobs:
  doc-remove:
    name: Remove preview documentation for PRs
    runs-on: ubuntu-latest

    steps:
      - name: Create documentation removing monitor
        run: |
          mkdir doc && cd doc
          echo "remove development PR-${{ github.event.number }}" > \
               "monitor_${GITHUB_RUN_ID}.txt"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: doc
          path: doc
