# Copyright (c) 2021 TiaC Systems
# SPDX-License-Identifier: Apache-2.0

name: QA License Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  qa-licenses:
    name: Run scancode for licenses
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Scan the code
        uses: zephyrproject-rtos/action_scancode@v3
        id: scancode
        with:
          directory-to-scan: 'scan/'

      - name: Upload results
        uses: actions/upload-artifact@v1
        with:
          name: scancode
          path: ./artifacts

      - name: Verify results
        run: |
          if [ -s ./artifacts/report.txt ]; then
            report=$(cat ./artifacts/report.txt)
            report="${report//'%'/'%25'}"
            report="${report//$'\n'/'%0A'}"
            report="${report//$'\r'/'%0D'}"
            echo "::error file=./artifacts/report.txt::$report"
            exit 1
          fi
