# Copyright (c) 2021 TiaC Systems
# Copyright (c) 2021 Li-Pro.Net
# SPDX-License-Identifier: Apache-2.0

name: QA Manifest Check and Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'west.yml'

jobs:
  qa-manifest:
    name: Run manifest checks points to patch series (PR)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          path: workspace/bridle
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run manifest check
        uses: zephyrproject-rtos/action-manifest@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          manifest-path: 'west.yml'
          checkout-path: 'workspace/bridle'
          label-prefix: 'manifest-'
          verbosity-level: '1'
          labels: 'manifest'
          dnm-labels: 'DNM'
